OT159 17
alkemyTech/OT159-Node-server pull request #11
Opened 2022-03-21 13:53 UTC by FernandaElola

Crear modelo, migración y controlador base de Users:

Descripción
Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
firstName: VARCHAR NOT NULL
lastName: VARCHAR NOT NULL
email: VARCHAR UNIQUE NOT NULL
password: VARCHAR NOT NULL
photo: VARCHAR NULLABLE
roleId: Clave foranea hacia ID de Role
timestamps y softDeletes

2022-03-25 03:47 UTC, maxxCeballos requested changes

2022-03-25 03:47 UTC, maxxCeballos commented on controllers/usersController.js
> +  },
No se solicita en ticket

2022-03-25 03:47 UTC, maxxCeballos commented on repositories/usersRepository.js
> +    return users
No se solicita en ticket

2022-03-26 19:15 UTC, FernandaElola commented on repositories/usersRepository.js
> +    return users
@maxxCeballos ya está hecho el push con estos cambios 👍

2022-03-26 19:17 UTC, FernandaElola commented on controllers/usersController.js
> +  },
codigo borrado

2022-03-26 21:51 UTC, maxxCeballos approved these changes

2022-03-27 01:07 UTC, closed without merging