Ot159 19
alkemyTech/OT159-Node-server pull request #12
Opened 2022-03-21 15:02 UTC by luisinaescobar

I have added the Post endpoint for news with the appropriate validations.

2022-03-25 04:42 UTC, maxxCeballos requested changes

2022-03-25 04:42 UTC, maxxCeballos commented on repositories/news.js
> +    }
Por el momento no utilicemos clases, solo funciones.

2022-03-25 04:42 UTC, maxxCeballos commented on controllers/controllerNews.js
> +const controllerNews = async function (req, res, next) {
Cambiar el nombre a uno mas apropiado para la tarea que realiza la funcion.

2022-03-25 04:42 UTC, maxxCeballos commented on controllers/controllerNews.js
> +        }
Las validaciones hacerlas en middleware (ruta, middlewareValidator, controller).

2022-03-25 04:42 UTC, maxxCeballos commented on controllers/controllerNews.js
> +            image: req.body.image
Extraer las variables del req al principio de la funcion con desestructuracion de objetos.

const { name, content, image } = req

Despues al objeto data lo podes armar simplemente con

data = { 
  name, 
  content, 
  image
}

2022-03-25 04:42 UTC, maxxCeballos commented on controllers/controllerNews.js
> +        data1 = await serviceNews.save(data);
1. Declarar las variables con let o const.
2. data1 no es un nombre declarativo, utilizar algo mas apropiado, por ejemplo newCreated.

2022-03-25 04:42 UTC, maxxCeballos commented on controllers/controllerNews.js
> +        throw new Error("something happened")
Este error se lanza en algun momento si hicimos next(error) en el paso previo?

2022-03-25 04:42 UTC, maxxCeballos commented on models/news.js
> +    modelName: 'New',
Falta declarar propiedad para softdelete. Dejo enlace

https://sequelize.org/master/manual/paranoid.html

2022-03-25 15:15 UTC, luisinaescobar commented on controllers/controllerNews.js
> +        throw new Error("something happened")
Hola maxi gracias por tus comentarios, son muy valiosos. El error de catch yo lo dejo por costumbre al usarlo con la estructura del try/catch pero no se lanza en ningun momento. Lo borro y dejo solo el try o saco tambien el try?

2022-03-29 02:52 UTC, maxxCeballos approved these changes

2022-03-29 11:55 UTC, merged