Ot159 20
alkemyTech/OT159-Node-server pull request #13
Opened 2022-03-21 19:34 UTC by JuanAvalo

Added model, migrations and base controllers of Testimonials
Includes Services and Repositories

Testimonials model fields:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
image: VARCHAR NULLABLE
content: VARCHAR NULLABLE
timestamps y softDeletes

2022-03-25 03:52 UTC, maxxCeballos requested changes

2022-03-25 03:52 UTC, maxxCeballos commented on controllers/testimonial.js
> +  }
No se solicita en el ticket

2022-03-25 03:52 UTC, maxxCeballos commented on controllers/testimonial.js
> +  }
No se solicita en ticket

2022-03-25 03:52 UTC, maxxCeballos commented on migrations/20220321183657-create-testimonial.js
> +        type: Sequelize.STRING
name no puede ser null

2022-03-25 03:52 UTC, maxxCeballos commented on repositories/testimonial.js
> +};
No se solicita en ticket

2022-03-25 03:52 UTC, maxxCeballos commented on services/testimonial.js
> +};
no se solicita en ticket

2022-03-25 18:58 UTC, JuanAvalo commented on migrations/20220321183657-create-testimonial.js
> +        type: Sequelize.STRING
se agrego allowNull: false

2022-03-25 18:58 UTC, JuanAvalo commented on controllers/testimonial.js
> +  }
removido

2022-03-29 03:16 UTC, maxxCeballos approved these changes

2022-03-29 04:24 UTC, merged