Ot159 69
alkemyTech/OT159-Node-server pull request #16
Opened 2022-03-21 22:52 UTC by JuanAvalo

Added endpoint POST /testimonials
Verifies that 'name' and 'content' are not empty before saving in the db.

Added testimonial Routes
Installed express-validator dependencies

2022-03-25 04:08 UTC, maxxCeballos requested changes

2022-03-25 04:08 UTC, maxxCeballos commented on controllers/testimonial.js
> +      image,
que pasa si image viene vacio?

2022-03-25 04:08 UTC, maxxCeballos commented on controllers/testimonial.js
> +    return res.status(200).send(newTestimonial);
Cuando se crea un recurso el status code apropiado es 201.

2022-03-25 04:08 UTC, maxxCeballos commented on services/testimonial.js
> +};
Fuera del alcance del ticket

2022-03-25 04:08 UTC, maxxCeballos commented on controllers/testimonial.js
> +    res.status(400).send(error);
por que 400 de respuesta? 400 indica un badrequest

2022-03-25 20:19 UTC, JuanAvalo commented on controllers/testimonial.js
> +};
removido

2022-03-25 20:20 UTC, JuanAvalo commented on models/testimonial.js
> +};
removido

2022-03-25 20:21 UTC, JuanAvalo commented on migrations/20220321183657-create-testimonial.js
> +  }
removido

2022-03-25 20:41 UTC, JuanAvalo commented on controllers/testimonial.js
> +    return res.status(200).send(newTestimonial);
modificado a 201

2022-03-25 20:42 UTC, JuanAvalo commented on services/testimonial.js
> +};
removido

2022-03-26 02:45 UTC, JuanAvalo commented on controllers/testimonial.js
> +      image,
Se deja validacion solo para 'name' como se definio en el modelo

2022-03-26 02:46 UTC, JuanAvalo commented on controllers/testimonial.js
> +    res.status(400).send(error);
Se cambio a 500

2022-03-29 03:20 UTC, maxxCeballos approved these changes

2022-03-29 23:32 UTC, Luitmate commented
@maxxCeballos Este branch tiene un conflicto con el main.

2022-03-30 03:38 UTC, merged