Ot159 74
alkemyTech/OT159-Node-server pull request #17
Opened 2022-03-22 21:32 UTC by luispatriciomedinavargas

COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.

Criterios de aceptación:
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-03-25 18:03 UTC, maxxCeballos requested changes

2022-03-25 18:03 UTC, maxxCeballos commented on middlewares/validar-campos.js
> +    }
que se valida aca?

2022-03-30 01:59 UTC, luispatriciomedinavargas commented on app.js
>  app.use('/', indexRouter);
esto da error porque esta declarada la ruta de members

2022-03-30 02:00 UTC, luispatriciomedinavargas commented on app.js
> -
esto da error porque esta declarada la ruta de members

2022-03-31 23:57 UTC, maxxCeballos requested changes

2022-03-31 23:57 UTC, maxxCeballos commented on middlewares/memberMidldlewar.js
> +    check('image','the image most be String').isString(),
solo debe validar el campo name

2022-03-31 23:57 UTC, maxxCeballos commented on controlers/membersController.js
> +    })
colocar dentro de un try/catch para el manejo de errores

2022-03-31 23:57 UTC, maxxCeballos commented on controlers/membersController.js
> +    })
colocar dentro de un try/catch para el manejo de errores

2022-04-01 00:06 UTC, luispatriciomedinavargas commented on middlewares/memberMidldlewar.js
> +    check('image','the image most be String').isString(),
En el modelo pide que Image sea obligatorio, por eso se lo valido image

2022-04-01 00:17 UTC, maxxCeballos approved these changes

2022-04-01 15:12 UTC, merged