#18 Crear modelo, migración y controlador base de Categories Descripción …
alkemyTech/OT159-Node-server pull request #18
Opened 2022-03-23 17:48 UTC by omaroaburto

#18
Campos: id: INTEGER NOT NULL AUTO_INCREMENT name: VARCHAR NOT NULL description: VARCHAR NULLABLE image: VARCHAR NULLABLE timestamps y softDeletes

2022-03-25 17:26 UTC, maxxCeballos requested changes

2022-03-25 17:26 UTC, maxxCeballos commented on models/categories.js
> +    timestamps: true,
Falta declarar [softDelete](https://sequelize.org/master/manual/paranoid.html)

2022-03-25 17:26 UTC, maxxCeballos commented on seeders/20220323011236-create-categories.js
> +  },
Esta fuera del alcance del ticket

2022-03-25 17:26 UTC, maxxCeballos commented on migrations/20220322235742-create-category.js
> +  });
Esta logica es del modelo, no de migration

2022-03-28 02:20 UTC, omaroaburto commented on models/categories.js
> +    timestamps: true,
se realizaron los cambios sugeridos en el modelo

2022-03-28 02:20 UTC, omaroaburto commented on seeders/20220323011236-create-categories.js
> +  },
se eliminó el archivo

2022-03-28 02:21 UTC, omaroaburto commented on migrations/20220322235742-create-category.js
> +  });
se corrigieron los errores en la migration

2022-03-29 03:29 UTC, maxxCeballos requested changes

2022-03-29 03:29 UTC, maxxCeballos commented on models/categories.js
> +  });
Omaro, mucho mejor! Falta declarar el [softDelete](https://sequelize.org/master/manual/paranoid.html)

2022-03-29 05:59 UTC, omaroaburto commented on models/categories.js
> +  });
se agrega al declaraciòn de softDelete

2022-03-29 21:08 UTC, merged