Ot159 #43 Endpoint Creación Categorías Descripción COMO usuario administrador Q…
alkemyTech/OT159-Node-server pull request #19
Opened 2022-03-23 20:39 UTC by omaroaburto

Ot159 #43
Endpoint Creación Categorías Descripción COMO usuario administrador QUIERO agregar una categoría nueva al sistema PARA categorizar las Novedades Criterios de aceptación: POST /categories - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-03-25 17:40 UTC, maxxCeballos requested changes

2022-03-25 17:40 UTC, maxxCeballos commented on models/categories.js
> +  });
Esto pertenece al ticket 18

2022-03-25 17:40 UTC, maxxCeballos commented on middlewares/validateCategories.js
> +}
esto valida una categoria? o es una validacion general?

2022-03-25 17:40 UTC, maxxCeballos commented on routes/categories.js
> +            .custom(existCategoryName),
hacer la validacion en un middleware

2022-03-25 17:40 UTC, maxxCeballos commented on routes/categories.js
> +            .withMessage('the image is required.'),
no se solicita validar description ni image

2022-03-25 17:40 UTC, maxxCeballos commented on routes/categories.js
> +router.post('/',[
En el ticket especifica que un usuario administrador es quien puede crear el recurso, por lo tanto habria que haber una validacion de rol, por el momento puede ser un middleware checkRol que siempre devuelta true hasta que implementemos la logica de tokens

2022-03-25 17:40 UTC, maxxCeballos commented on models/index.js
> +db.categories = require('./categories')(sequelize, Sequelize.DataTypes);
por qué esta declaración?

2022-03-25 17:40 UTC, maxxCeballos commented on controllers/categoriesController.js
> +        res.status(200).json({
Un status code mas apropiado para la creacion de un recurso es 201.

2022-03-25 17:40 UTC, maxxCeballos commented on controllers/categoriesController.js
> +        const category = await categoryServiceCreate(req.body.name, req.body.description, req.body.image)
sacar las variables a utilizar al comenzar la funcion

(req, res) => {
   const { name, description, image } = req.body
  ...
}

2022-03-25 17:40 UTC, maxxCeballos commented on helpers/db-validators.js
> +};
no hacer consultas a la base de datos desde un helper, esto se realiza en la capa de datos. Por otro lado, por que se hace la validacion? no se solicita en el ticket.

2022-03-26 20:41 UTC, omaroaburto commented on helpers/db-validators.js
> +};
es un error de nombre de variable pero debería validar que el nombre de la categoría se único para que no se repita en la base de datos. Mi pregunta es si agrego la consulta a la base de datos en la capa de datos y si mantengo esa validación

2022-03-28 02:21 UTC, omaroaburto commented on models/categories.js
> +  });
se elimina el archivo que pertenece al ticket 18

2022-03-28 02:22 UTC, omaroaburto commented on routes/categories.js
> +router.post('/',[
se crea un middleware para validar rol

2022-03-28 02:23 UTC, omaroaburto commented on models/index.js
> +db.categories = require('./categories')(sequelize, Sequelize.DataTypes);
se elimina declaración

2022-03-28 02:24 UTC, omaroaburto commented on controllers/categoriesController.js
> +        res.status(200).json({
se actualiza status de 200 a 201

2022-03-28 02:27 UTC, omaroaburto commented on controllers/categoriesController.js
> +        const category = await categoryServiceCreate(req.body.name, req.body.description, req.body.image)
se crea un directorio llamado validators que contiene las validaciones de express-validator y el middleware correspondiente 
[](https://desktop.github.com/)lines (15 sloc)  576 Bytes
   
```
const {check} = require('express-validator'); 
const { validateCategory } = require('../middlewares/validateCategories');
const { isAdminRole, haveRole } = require('../middlewares/validateRoles');

const validateCreate = [
    isAdminRole, // valida que el usuario tenga el rol de administrador
    haveRole('ADMIN'), // valida tenga un rol de la lista
    check('name')
            .notEmpty()
            .withMessage('The name is required.') 
            .matches(/^[A-Za-z0-9 ñÑáéíóúÁÉÍÓÚ']+$/), 
    validateCategory
]

module.exports = {
    validateCreate
}
```

2022-03-28 02:28 UTC, omaroaburto commented on helpers/db-validators.js
> +};
se elimina archivo helper (se utilizaba para validar que el nombre de la categoría sea único)

2022-03-29 21:09 UTC, merged