Ot159 15
alkemyTech/OT159-Node-server pull request #2
Opened 2022-03-19 12:35 UTC by eferreccio

**first upload of these files:**

- controllers/organizationController.js
- models/organization.js
- migrations/20220319114234-create-organization.js

2022-03-25 03:34 UTC, maxxCeballos requested changes

2022-03-25 18:25 UTC, eferreccio commented on models/organization.js
> +    aboutUSText: DataTypes.STRING
Ahí lo modifiqué gracias por los enlaces

2022-03-25 18:25 UTC, eferreccio commented on migrations/20220319114234-create-organization.js
> +      }
corregido.

2022-03-29 02:57 UTC, maxxCeballos approved these changes

2022-03-29 04:22 UTC, merged