Ot159 46
alkemyTech/OT159-Node-server pull request #31
Opened 2022-03-31 23:26 UTC by luisinaescobar

endpiont id news

2022-04-02 00:16 UTC, maxxCeballos requested changes

2022-04-02 00:16 UTC, maxxCeballos commented on services/news.js
> +    return await findNewsById(id)
Lu aca tendrias que validar si lo que devuelve el repositorio es distinto de null. Fijate que en la [docu](https://sequelize.org/v7/class/src/model.js~Model.html#static-method-findByPk) dice que retorna **Promise<Model\|null>** es decir, Model si encontro el id y  si no encuentra el id que le pasas te devuelve null.

2022-04-02 00:16 UTC, maxxCeballos commented on services/news.js
> +    return await findNewsById(id)
Por otro lado, si no tuvieras que validar el valor de retorno del repositorio y quisieras devolver directamente el valor como estas haciendo ahora, el **await** esta de mas, ya que retornas derecho la promise del repositorio.  Por ejemplo, si copias este codigo en un archivo .js y lo ejecutas vas a ver que mantiene el mismo comportamiento

```
const controller = async () => {
    console.log(await service());
};


const service = async () => {
    
    return repository();
};


const repository = () => {

    return Promise.resolve('hola');

}


controller();
```

2022-04-02 00:16 UTC, maxxCeballos commented on controllers/controllerNews.js
> +        res.status(201).json(findNew);
El status code para este caso seria un 200. El 201 se utiliza cuando se esta creando un recurso. Dejo referencia donde se habla de los [status codes](https://developer.mozilla.org/es/docs/Web/HTTP/Status)

2022-04-02 01:23 UTC, luisinaescobar commented on services/news.js
> +    return await findNewsById(id)
Genial ! gracias!

2022-04-07 16:00 UTC, maxxCeballos commented on services/news.js
> +    return await findNewsById(id)
Falta arreglar lo primero que te comente. En caso de que no exista el usuario vas a devolver un 200 null. Seria mas apropiado devolver un 404 con un mensaje de not found

2022-04-07 16:02 UTC, maxxCeballos requested changes

2022-04-07 16:02 UTC, maxxCeballos commented on controllers/controllerNews.js
> +        res.status(200).json(findNew);
Si el id enviado no existe estas retornando un 200 con un body null. Para ese caso habria que retornar un 404 con un mensaje de not found.

2022-04-11 22:09 UTC, maxxCeballos approved these changes

2022-04-12 02:57 UTC, merged