Ot159 38
alkemyTech/OT159-Node-server pull request #37
Opened 2022-04-01 21:23 UTC by FernandaElola

Endpoint para actualización de datos públicos de Organización

COMO usuario administrador
QUIERO actualizar los datos públicos de la Organización
PARA mantener la información actualizada

Criterios de aceptación:
Petición POST hacia ruta /organization/public

Solamente el usuario administrador podrá editar los datos públicos de la Organización. Deberá validar los campos requeridos y el formato correcto de los mismos

** NOTA **
// Agrego petición PUT hacia ruta /organization/public/:id con validaciones de formato de input para cumplir con el título del ticket.

2022-04-05 03:53 UTC, maxxCeballos requested changes

2022-04-05 03:53 UTC, maxxCeballos commented on controllers/organizationController.js
> +        const update = await organizationServices.update(organizationData, req.params.id)
update es un nombre muy general, utilizar un nombre mas especifico, por ejemplo, organizationUpdated.
Por otro lado, validar la respuesta para saber si se modifico un recurso, caso contrario retornar 404.

2022-04-05 17:15 UTC, FernandaElola commented on controllers/organizationController.js
> +        const update = await organizationServices.update(organizationData, req.params.id)
Listo! Modifiqué además el nombre en create porque tenía el mismo problema.
También hice algunos cambios en el código para que quede mas fácil de leer.

2022-04-07 19:02 UTC, maxxCeballos approved these changes

2022-04-07 21:13 UTC, merged