Ot159 42
alkemyTech/OT159-Node-server pull request #38
Opened 2022-04-01 21:26 UTC by FernandaElola

Endpoint Detalle Categoría

COMO usuario administrador
QUIERO obtener información de una categoría individual
PARA poder gestionarla

Criterios de aceptación:
GET a /categories/:id . Mostrará todos los campos de una categoría en base al id enviado por parámetro. En el caso de que no exista, devolverá un error con un código de estado 404

2022-04-04 20:15 UTC, maxxCeballos requested changes

2022-04-04 20:15 UTC, maxxCeballos commented on controllers/categoriesController.js
> +        const category = await categoryServiceDetail(req.params.id)
extraer las variables del req al comienzo de la funcion:
const { id } = req.params

2022-04-04 20:15 UTC, maxxCeballos commented on controllers/categoriesController.js
> +        return res.status(201).send(category);
Utilizar 200 para este caso, 201 es cuando creamos un recurso nuevo.

2022-04-04 21:32 UTC, FernandaElola commented on controllers/categoriesController.js
> +        const category = await categoryServiceDetail(req.params.id)
Cambio realizado.

2022-04-04 21:33 UTC, FernandaElola commented on controllers/categoriesController.js
> +        return res.status(201).send(category);
Status modificado.

2022-04-07 19:00 UTC, maxxCeballos approved these changes

2022-04-07 21:15 UTC, merged