list member controller added
alkemyTech/OT159-Node-server pull request #40
Opened 2022-04-02 18:42 UTC by eferreccio

**List members**

**files changed**

- controllers/membersController.js
- repositories/memberRepository.js
- routes/members.js
- services/memberService.js

2022-04-05 02:54 UTC, maxxCeballos requested changes

2022-04-05 02:54 UTC, maxxCeballos commented on routes/members.js
> +router.get('/', listMembers.list)
Un usuario administrador puede realizar esta accion, por lo tanto se debe agregar middleware para chequear el Rol de admin.

2022-04-05 02:54 UTC, maxxCeballos commented on controllers/membersController.js
> +        res.json(response);
Utilizar try/catch para el caso de que ocurra un error, por ejemplo un error de conexion con la base de datos o un timeout cuando la consulta tarda mucho.

2022-04-05 12:41 UTC, eferreccio commented on routes/members.js
> +router.get('/', listMembers.list)
isAdmin middleware agregado.

2022-04-05 12:42 UTC, eferreccio commented on controllers/membersController.js
> +        res.json(response);
agregado el try cacth al método listMembers.list

2022-04-07 20:02 UTC, maxxCeballos requested changes

2022-04-07 20:02 UTC, maxxCeballos commented on controllers/membersController.js
> +            })
no dejar console.log en produccion.
por qué 504?

2022-04-07 20:02 UTC, maxxCeballos commented on services/memberService.js
> +const memberServiceList = (data) => {
Aca la funcion declara que recibe como parametro data. Pero en la llamada de la funcion desde el controller no se esta enviando ningun argumento en la funcion.

2022-04-07 20:52 UTC, eferreccio commented on controllers/membersController.js
> +            })
Cambiado a 500.

2022-04-07 20:53 UTC, eferreccio commented on services/memberService.js
> +const memberServiceList = (data) => {
Corregido. No hacía falta mandar el path a service y repository

2022-04-07 22:44 UTC, maxxCeballos approved these changes

2022-04-08 01:24 UTC, merged