Ot159 50
alkemyTech/OT159-Node-server pull request #41
Opened 2022-04-03 00:58 UTC by JuanAvalo

COMO usuario administrador
QUIERO eliminar una actividad existente
PARA mantener la información actualizada

Criterios de aceptación:
DELETE /news/:id - Deberá validar la existencia en base al id enviado por parámetro. En el caso de que exista, eliminarla

2022-04-05 03:20 UTC, maxxCeballos requested changes

2022-04-05 03:20 UTC, maxxCeballos commented on repositories/news.js
> +    const deletedNew = await foundNew.destroy();
Se puede lograr la misma logica con una sola consulta a la base de datos. En base a la respuesta del destroy() vos podes validar ese resultado y saber si elimino o no un registro de la base de datos.
De todos modos, esta validacion la haria en la capa de servicio, lo vemos en la daily cualquier cosa.

2022-04-05 03:20 UTC, maxxCeballos commented on services/news.js
> +  }
Este try/catch se podria "relajar". Vos en el controller ya tener una clausula de try/catch que va a estar catcheando cualquier error que suceda aca, entonces en lugar de catchear y volver a lanzarlo como estas haciendo aca, dejas que haga un "bubble up" y lo catcheas en el controller.

2022-04-05 15:36 UTC, avalojuan commented on repositories/news.js
> +    const deletedNew = await foundNew.destroy();
Se removio el findByPk
Se agrego la validacion del destroy en services
Se mejoro los mensajes de error

2022-04-05 15:36 UTC, JuanAvalo commented on services/news.js
> +  }
Se removio el try/catch y se mejoro el mensaje de error en el controller

2022-04-07 20:06 UTC, maxxCeballos approved these changes

2022-04-07 21:16 UTC, merged