Ot159 52 endpoint creacion actividades
alkemyTech/OT159-Node-server pull request #43
Opened 2022-04-03 08:47 UTC by Luitmate

Se borraron algunas líneas que tenían que ver con un ticket anterior (OT159-21) en donde se hacían funciones get y getById que no tenían que ver con ese ticket.

2022-04-04 20:30 UTC, maxxCeballos requested changes

2022-04-04 20:30 UTC, maxxCeballos commented on routes/activities.js
> +router.post('/', validateActivities, createNewActivity)
Un usuario administrador es quien puede crear activities por lo tanto falta agregar middle de check de Rol para validar el permiso.

2022-04-04 20:30 UTC, maxxCeballos commented on services/activitiesService.js
> -const repository = new ActivityRepository();
Esto no esta en main, por que aparece?

2022-04-05 00:42 UTC, Luitmate commented on services/activitiesService.js
> -const repository = new ActivityRepository();
Esto estaba en el main cuando cree mi branch, fue mergeado en el PR #6  (ticket 159-21)

2022-04-05 01:28 UTC, Luitmate commented on routes/activities.js
> +router.post('/', validateActivities, createNewActivity)
Agregado isAdminRole middleware

2022-04-07 19:03 UTC, maxxCeballos approved these changes

2022-04-07 21:41 UTC, merged