Ot159 71 Endpoint eliminación de Testimonios
alkemyTech/OT159-Node-server pull request #60
Opened 2022-04-06 19:51 UTC by omaroaburto

Descripción
COMO usuario administrador
QUIERO eliminar Testimonios
PARA moderar los Testimonios y Novedades acerca de la ONG.

Criterios de aceptación:
Cuando el usuario se registre en el sitio, deberá loguearse automáticamente y redirigirse a la ruta base(/). Para ello, es necesario modificar el servidor para que devuelva el token una vez creado el usuario, y almacenar el mismo en el lado del cliente

2022-04-07 19:15 UTC, maxxCeballos requested changes

2022-04-07 19:15 UTC, maxxCeballos commented on controllers/testimonial.js
> +    const testimonial = testimonialService.remove(id)(testimonial == 0)
esto te anduvo? no entiendo el segundo parentesis. Por otro lado no utilizas un await por lo tanto no se espera la respuesta del servicio.

2022-04-07 19:24 UTC, omaroaburto commented on controllers/testimonial.js
> +    const testimonial = testimonialService.remove(id)(testimonial == 0)
se corrigió el error, subi otro archivo.

2022-04-11 23:38 UTC, maxxCeballos requested changes

2022-04-11 23:38 UTC, maxxCeballos commented on controllers/testimonial.js
> +    if(testimonial == 0){
Aca no seria 1 en caso de que se borre correctamente?
Por otro lado utilizar siempre === en lugar de ==

2022-04-12 00:25 UTC, omaroaburto commented on controllers/testimonial.js
> +    if(testimonial == 0){
se corrigió

2022-04-12 20:31 UTC, maxxCeballos approved these changes

2022-04-12 21:28 UTC, merged