added user put but still does not work fine
alkemyTech/OT159-Node-server pull request #69
Opened 2022-04-11 23:45 UTC by luispatriciomedinavargas

2022-04-12 01:04 UTC, luispatriciomedinavargas commented on middlewares/validations/user.js
> +
El modelo de usuario no pedía ningún campo como obligatorio, asi que simplemente se valido que sean del tipo correcto

2022-04-19 20:41 UTC, maxxCeballos requested changes

2022-04-19 20:41 UTC, maxxCeballos commented on controllers/usersController.js
> +  res.status(404).json({
aca el 404 se lanza por cualquier error que pueda ocurrir, no solo si el usuario no se encontro. El 404 se Debe lanzar solo en caso de no encontrar el recurso solicitado con el id

2022-04-19 20:41 UTC, maxxCeballos commented on controllers/usersController.js
> +  pathUser: async(req = request, res = response)=>{
pathUser no es descriptivo sobre lo que hace la funcion, utilizar un nombre mas apropiado

2022-04-20 01:49 UTC, maxxCeballos requested changes

2022-04-20 01:49 UTC, maxxCeballos commented on services/usersService.js
> +    if (checkPathUser[0]===0) throw new Error
Aca es el caso donde deberia devolver un 404, lo podes lanzar desde aca, o podes hacer esta misma validacion en el controller y aprovechar el objeto `res` para hacer res.status(404)

2022-04-21 00:17 UTC, closed without merging