Ot159 23
alkemyTech/OT159-Node-server pull request #9
Opened 2022-03-21 01:09 UTC by eferreccio

**Create organization/public request**

2 new files adding:

- organizationServices.js
- organizationRepository.js

Logic of showData method on OrganizationController.js added.

2022-03-25 02:34 UTC, maxxCeballos requested changes

2022-03-25 02:34 UTC, maxxCeballos commented on migrations/20220319114234-create-organization.js
> +};
Estos cambios pertencen al ticket 15, no deberian estar en este PR.

2022-03-25 02:34 UTC, maxxCeballos commented on models/organization.js
> +};
Estos cambios pertencen al ticket 15, no deberian estar en este PR.

2022-03-25 02:34 UTC, maxxCeballos commented on controllers/organizationController.js
> +        })
En lugar de hacer esta iteración se pueden obtener directamente los campos solicitados desde la base de datos. Te dejo un enlace donde donde muestra consultas con [select](https://sequelize.org/master/manual/model-querying-basics.html#simple-select-queries)

2022-03-25 16:52 UTC, eferreccio commented on migrations/20220319114234-create-organization.js
> +};
Maxi, listo, ya hice el commit borrando esto. (justo el ticket 15 me había tocado a mi, por eso lo subí, pero entiendo el sentido de borrarlo).

2022-03-29 03:01 UTC, maxxCeballos approved these changes

2022-03-29 23:32 UTC, Luitmate commented
@maxxCeballos Este branch tiene un conflicto con el main.

2022-03-30 03:37 UTC, merged