Ot159 64
alkemyTech/OT159-Node-server pull request #91
Opened 2022-04-16 03:56 UTC by luisinaescobar

Enviar email de contacto
COMO usuario 
QUIERO recibir un correo cuando me contacto
PARA confirmar que he completado el contacto con éxito.

Criterios de aceptación:
Cuando se registre un nuevo contacto en el sitio, enviar un email al usuario que completó el formulario agradeciendo su contacto. Para esto, utilizar el servicio de envío de emails.

2022-04-20 11:50 UTC, luisinaescobar commented
Listo Maxi, cambie el nombre de la función y la reutilice en los servicios para la creación de contactos.
Saludos!

2022-04-21 03:44 UTC, maxxCeballos requested changes

2022-04-21 03:44 UTC, maxxCeballos commented on controllers/contacts.js
> +const sendedEmail = await sendMailNewContact(mail)
Lu fijate que en controllers en la rama dev ya hay un contactController donde hay una funcion create, declarada asi:
```
const create = async(req, res, next) => {
    try {
        const { name, phone, email, message } = req.body
        const newContact = await contactsService.create({name, phone, email, message})
        res.stauts(200).json(newContact)
    } catch (error) {
        next(error)
    }
}
```

Justo debajo del const newContact = ... es donde tenes que agregar la llamada a la funcion de envio de email, es decir, cuando creamos un contacto entonces enviamos el emaill.

2022-04-21 12:52 UTC, luisinaescobar commented on controllers/contacts.js
> +const sendedEmail = await sendMailNewContact(mail)
Hola maxi... en mi rama no tengo esos cambios... voy a hacer lo siguiente borro ese archivo contacts.js y en otra rama lo incluyo en el controller q me dijiste..

2022-04-21 13:00 UTC, luisinaescobar commented on controllers/contacts.js
> +const sendedEmail = await sendMailNewContact(mail)
La rama se llama V1ot159-64

2022-04-21 23:24 UTC, maxxCeballos approved these changes

2022-04-21 23:26 UTC, merged